import { notFound, redirect } from 'next/navigation';
import { prisma } from '@/lib/db';
import { createClient } from '@/lib/supabase/server';
import { SummaryDisplay } from '@/components/summary-display';
import { ChatInterface } from '@/components/chat-interface';
import { DeleteArticleButton } from '@/components/delete-article-button';
import { Button } from '@/components/ui/button';
import { ExternalLink, Calendar, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

interface PageProps {
  params: Promise<{
    id: string;
  }>;
}

export default async function ArticlePage({ params }: PageProps) {
  const { id } = await params;

  // Check authentication
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // Get article with ownership check
  const article = await prisma.article.findUnique({
    where: { id },
    select: {
      id: true,
      title: true,
      url: true,
      summary: true,
      createdAt: true,
      userId: true,
    },
  });

  if (!article) {
    notFound();
  }

  // Enforce ownership: only the owner can view their articles
  if (article.userId && article.userId !== user?.id) {
    redirect('/dashboard');
  }

  // For articles without userId (legacy/anonymous), allow public access
  // but encourage login for saving
  const isOwner = user && article.userId === user.id;

  let summary;
  try {
    summary = JSON.parse(article.summary);
  } catch {
    summary = { tldr: [], takeaways: [], outline: [] };
  }

  return (
    <div className="min-h-screen gradient-mesh">
      <div className="container mx-auto px-4 py-6 max-w-[1600px]">
        {/* Article Header */}
        <div className="mb-6 space-y-3">
          <div className="flex items-center gap-3 mb-4">
            <Link href="/dashboard">
              <Button variant="ghost" size="icon" className="hover:bg-primary/5">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <span>Back to Dashboard</span>
            </div>
          </div>
          <div className="flex items-start justify-between gap-4">
            <h1 className="text-3xl md:text-4xl font-bold leading-tight flex-1">
              {article.title}
            </h1>
            <div className="flex items-center gap-2 shrink-0">
              <a
                href={article.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 px-4 py-2 rounded-lg border border-border/50 bg-card/50 hover:bg-card hover:border-primary/20 transition-all hover:scale-105"
              >
                <ExternalLink className="h-4 w-4 text-primary" />
                <span className="text-sm font-medium">Original</span>
              </a>
              {isOwner && (
                <DeleteArticleButton
                  articleId={article.id}
                  articleTitle={article.title}
                  variant="outline"
                  size="default"
                />
              )}
            </div>
          </div>
          <div className="flex items-center gap-4 text-sm text-muted-foreground">
            <div className="flex items-center gap-2">
              <Calendar className="h-4 w-4" />
              <span>{new Date(article.createdAt).toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}</span>
            </div>
            <a
              href={article.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline truncate max-w-md"
            >
              {article.url}
            </a>
          </div>
        </div>

        {/* Split Layout: Summary Left, Chat Right */}
        <div className="flex flex-col lg:flex-row gap-6 items-start">
          {/* Left Column: TL;DR, Key Takeaways, and Outline stacked vertically */}
          <div className="flex-1 space-y-4 min-w-0 w-full lg:w-auto">
            <SummaryDisplay
              title={article.title}
              summary={summary}
              url={article.url}
            />
            <div className="p-4 rounded-lg bg-card/50 border border-border/50 text-sm text-muted-foreground">
              <p>
                This summary was generated by AI. Verify important facts with the
                original article.
              </p>
            </div>
          </div>

          {/* Right Column: Chat Interface - Sticky */}
          <div className="w-full lg:w-[420px] lg:sticky lg:top-20 shrink-0">
            <ChatInterface articleId={article.id} />
          </div>
        </div>
      </div>
    </div>
  );
}

// Generate metadata for SEO
export async function generateMetadata({ params }: PageProps) {
  const { id } = await params;
  
  const article = await prisma.article.findUnique({
    where: { id },
    select: { title: true },
  });

  if (!article) {
    return {
      title: 'Article Not Found',
    };
  }

  return {
    title: `${article.title} - ArticleIQ`,
    description: `AI-generated summary and insights for: ${article.title}`,
  };
}

